services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile.dev
    volumes:
      - ./rustflix/src:/usr/src/rustflix/src
      - ./rustflix/Cargo.toml:/usr/src/rustflix/Cargo.toml
      - ./rustflix/Cargo.lock:/usr/src/rustflix/Cargo.lock
    ports:
      - "8087:8080"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/rustflix
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rustflix
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  postgres_data:
